parameters:
    overheidurl: "https://api.overheid.io/voertuiggegevens"
    overheidapikey: "9f2433bb9542d82f552da126d7290b31b55bf87ecae6911f0df0765758b88f62"

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    
    App\Service\Client\OverheidClient:
        arguments:
            $baseUrl: "%overheidurl%"
            $apiKey: "%overheidapikey%"
    
    App\Service\Client\CarClient:
        parent: App\Service\Client\OverheidClient
